//! Phase 36U state I/O real-backend read-probe facade.
//!
//! This module is intentionally side-effect free. It models how the future
//! SD/FAT-backed state backend should probe for existing typed state records,
//! but it does not open files, read blocks, access SPI, update display state,
//! or change runtime boot behavior.

/// Phase 36U acceptance marker.
pub const PHASE_36U_STATE_IO_REAL_BACKEND_READ_PROBE_MARKER: &str =
    "phase36u=x4-state-io-real-backend-read-probe-ok";

/// Human-readable phase name.
pub const PHASE_36U_STATE_IO_REAL_BACKEND_READ_PROBE_NAME: &str =
    "Phase 36U — State I/O Real Backend Read Probe Overlay";

/// Maximum number of candidate paths the real backend may check per logical
/// read in the first implementation lane.
pub const MAX_READ_PROBE_CANDIDATES: usize = 3;

/// Logical state record handled by the future backend read probe.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StateReadProbeRecordKind {
    /// Per-book progress state: `state/<BOOKID>.PRG`.
    Progress,
    /// Per-book theme/layout state: `state/<BOOKID>.THM`.
    Theme,
    /// Per-book metadata state: `state/<BOOKID>.MTA`.
    Metadata,
    /// Per-book bookmarks state: `state/<BOOKID>.BKM`.
    Bookmark,
    /// Global bookmark index: `state/BMIDX.TXT`.
    BookmarkIndex,
}

impl StateReadProbeRecordKind {
    /// Returns the canonical 8.3-safe extension or file name for this record.
    pub const fn storage_suffix(self) -> &'static str {
        match self {
            Self::Progress => ".PRG",
            Self::Theme => ".THM",
            Self::Metadata => ".MTA",
            Self::Bookmark => ".BKM",
            Self::BookmarkIndex => "BMIDX.TXT",
        }
    }

    /// Returns whether this record is per-book scoped.
    pub const fn is_per_book(self) -> bool {
        !matches!(self, Self::BookmarkIndex)
    }
}

/// The intended read mode for a future backend operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StateReadProbeMode {
    /// Read the canonical state file only.
    CanonicalOnly,
    /// Read canonical first, then allow a recovery candidate if needed.
    CanonicalWithRecovery,
    /// Probe all known candidates without selecting a final read target.
    InventoryOnly,
}

/// A candidate path classification for the future backend probe.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StateReadProbeCandidateRole {
    /// The normal canonical file path.
    Canonical,
    /// A previous backup generated by a future shadow-write lane.
    Backup,
    /// A temporary file left by an interrupted future write.
    Temporary,
}

/// Result of checking one candidate path.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StateReadProbeCandidateStatus {
    /// Candidate was not checked in this side-effect-free phase.
    NotChecked,
    /// Candidate exists and can be read by a future backend.
    Readable,
    /// Candidate is absent.
    Missing,
    /// Candidate exists but is not usable.
    Invalid,
}

/// Final read-probe decision for a future backend operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StateReadProbeDecision {
    /// The future backend should use the canonical record.
    UseCanonical,
    /// The future backend should try a backup/recovery candidate.
    TryRecoveryCandidate,
    /// The future backend should return an empty/default state.
    ReturnDefaultState,
    /// The future backend should report a recoverable read error.
    ReportRecoverableError,
}

/// Side-effect-free candidate descriptor.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct StateReadProbeCandidate {
    /// Candidate role.
    pub role: StateReadProbeCandidateRole,
    /// Candidate status.
    pub status: StateReadProbeCandidateStatus,
    /// Logical path label. This is metadata only, not an opened path handle.
    pub path_label: &'static str,
}

impl StateReadProbeCandidate {
    /// Creates a candidate descriptor.
    pub const fn new(
        role: StateReadProbeCandidateRole,
        status: StateReadProbeCandidateStatus,
        path_label: &'static str,
    ) -> Self {
        Self {
            role,
            status,
            path_label,
        }
    }
}

/// Side-effect-free read-probe request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct StateReadProbeRequest {
    /// Record kind to probe.
    pub record_kind: StateReadProbeRecordKind,
    /// Read mode for the future backend.
    pub mode: StateReadProbeMode,
    /// Whether the operation is guaranteed read-only.
    pub read_only: bool,
}

impl StateReadProbeRequest {
    /// Creates a canonical read-only probe request.
    pub const fn canonical(record_kind: StateReadProbeRecordKind) -> Self {
        Self {
            record_kind,
            mode: StateReadProbeMode::CanonicalOnly,
            read_only: true,
        }
    }

    /// Creates a recovery-capable read-only probe request.
    pub const fn with_recovery(record_kind: StateReadProbeRecordKind) -> Self {
        Self {
            record_kind,
            mode: StateReadProbeMode::CanonicalWithRecovery,
            read_only: true,
        }
    }
}

/// Side-effect-free read-probe response.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct StateReadProbeResponse {
    /// Request that produced this response.
    pub request: StateReadProbeRequest,
    /// Probe decision.
    pub decision: StateReadProbeDecision,
    /// Candidate count represented in this response.
    pub candidate_count: usize,
    /// Read safety marker.
    pub read_only_confirmed: bool,
    /// Phase marker associated with this response.
    pub marker: &'static str,
}

impl StateReadProbeResponse {
    /// Returns whether the response is valid for the side-effect-free phase.
    pub const fn is_side_effect_free(self) -> bool {
        self.read_only_confirmed && self.request.read_only
    }
}

/// Returns the candidate-count limit accepted by this phase.
pub const fn accepted_candidate_limit() -> usize {
    MAX_READ_PROBE_CANDIDATES
}

/// Builds a side-effect-free default probe response for a request.
pub const fn describe_read_probe(request: StateReadProbeRequest) -> StateReadProbeResponse {
    let decision = match request.mode {
        StateReadProbeMode::CanonicalOnly => StateReadProbeDecision::ReturnDefaultState,
        StateReadProbeMode::CanonicalWithRecovery => StateReadProbeDecision::TryRecoveryCandidate,
        StateReadProbeMode::InventoryOnly => StateReadProbeDecision::ReportRecoverableError,
    };

    StateReadProbeResponse {
        request,
        decision,
        candidate_count: 0,
        read_only_confirmed: true,
        marker: PHASE_36U_STATE_IO_REAL_BACKEND_READ_PROBE_MARKER,
    }
}

/// Returns the phase marker.
pub const fn phase36u_marker() -> &'static str {
    PHASE_36U_STATE_IO_REAL_BACKEND_READ_PROBE_MARKER
}

/// Returns the phase name.
pub const fn phase36u_name() -> &'static str {
    PHASE_36U_STATE_IO_REAL_BACKEND_READ_PROBE_NAME
}
