#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-$(pwd)}"
CURRENT_DIR_NAME="vaachak_final_docs_cleanup"
CURRENT_ZIP_NAME="vaachak_final_docs_cleanup.zip"
PRUNE_OLD_VALIDATORS="false"

for arg in "${@:2}"; do
  case "$arg" in
    --prune-old-validators) PRUNE_OLD_VALIDATORS="true" ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

cd "$ROOT"

removed=0

safe_rm_dir() {
  local path="$1"
  if [ -d "$path" ]; then
    rm -rf "$path"
    removed=$((removed + 1))
  fi
}

safe_rm_file() {
  local path="$1"
  if [ -f "$path" ]; then
    rm -f "$path"
    removed=$((removed + 1))
  fi
}

# Remove extracted overlay folders. A generated overlay folder always has both
# MANIFEST.txt and README-APPLY.md at its root. This avoids deleting real repo
# directories such as docs, scripts, vendor, core, or target-xteink-x4.
for dir in ./*; do
  [ -d "$dir" ] || continue
  base="$(basename "$dir")"
  case "$base" in
    .git|core|docs|scripts|target|target-xteink-x4|tools|vendor|src|examples|tests|assets|firmware|hal-xteink-x4)
      continue
      ;;
    "$CURRENT_DIR_NAME")
      continue
      ;;
  esac
  if [ -f "$dir/MANIFEST.txt" ] && [ -f "$dir/README-APPLY.md" ]; then
    safe_rm_dir "$dir"
  fi
done

# Remove generated overlay zips. We only remove zips that contain the same
# MANIFEST.txt + README-APPLY.md sentinel used by the deliverable generator.
if command -v unzip >/dev/null 2>&1; then
  for zip in ./*.zip; do
    [ -f "$zip" ] || continue
    base="$(basename "$zip")"
    [ "$base" = "$CURRENT_ZIP_NAME" ] && continue
    if unzip -l "$zip" 2>/dev/null | awk '{print $4}' | grep -Eq '(^|/)MANIFEST\.txt$' \
      && unzip -l "$zip" 2>/dev/null | awk '{print $4}' | grep -Eq '(^|/)README-APPLY\.md$'; then
      safe_rm_file "$zip"
    fi
  done
fi

# Remove accidental Python cache folders under the repo. These are generated by
# patch/apply helpers and should not be committed.
find . -type d -name '__pycache__' -prune -print0 2>/dev/null | while IFS= read -r -d '' cache_dir; do
  rm -rf "$cache_dir"
done

# Remove temporary patch/apply/fix scripts that may have been copied into the
# repo scripts directory by older deliverables. Keep canonical validate_* and
# cleanup_* scripts unless the optional validator prune flag is used.
if [ -d scripts ]; then
  find scripts -maxdepth 1 -type f \( \
    -name 'patch_*.py' -o \
    -name 'apply_*_fix.sh' -o \
    -name 'apply_*_overlay.sh' -o \
    -name '*validator_fix*.sh' -o \
    -name '*_fmt_fix.sh' \
  \) -print0 | while IFS= read -r -d '' temp_script; do
    rm -f "$temp_script"
  done
fi

# Optional: prune superseded validators. This is intentionally opt-in because
# keeping validators is useful while reviewing the migration history.
if [ "$PRUNE_OLD_VALIDATORS" = "true" ] && [ -d scripts ]; then
  keep_regex='validate_(vaachak_hardware_runtime_final_acceptance|hardware_physical_full_migration_consolidation|hardware_physical_full_migration_cleanup|pulp_hardware_reference_deprecation_audit|pulp_hardware_dead_path_quarantine|pulp_hardware_dead_path_removal|vendor_pulp_os_scope_reduction|docs_and_artifact_cleanup)\.sh$'
  find scripts -maxdepth 1 -type f -name 'validate_*.sh' -print0 | while IFS= read -r -d '' validator; do
    base="$(basename "$validator")"
    if ! printf '%s\n' "$base" | grep -Eq "$keep_regex"; then
      rm -f "$validator"
    fi
  done
fi

# Count remaining generated overlay artifacts for visibility. Do not fail on the
# current overlay folder/zip because the user may still be applying it.
remaining_dirs=0
for dir in ./*; do
  [ -d "$dir" ] || continue
  base="$(basename "$dir")"
  [ "$base" = "$CURRENT_DIR_NAME" ] && continue
  if [ -f "$dir/MANIFEST.txt" ] && [ -f "$dir/README-APPLY.md" ]; then
    remaining_dirs=$((remaining_dirs + 1))
  fi
done

remaining_zips=0
if command -v unzip >/dev/null 2>&1; then
  for zip in ./*.zip; do
    [ -f "$zip" ] || continue
    base="$(basename "$zip")"
    [ "$base" = "$CURRENT_ZIP_NAME" ] && continue
    if unzip -l "$zip" 2>/dev/null | awk '{print $4}' | grep -Eq '(^|/)MANIFEST\.txt$' \
      && unzip -l "$zip" 2>/dev/null | awk '{print $4}' | grep -Eq '(^|/)README-APPLY\.md$'; then
      remaining_zips=$((remaining_zips + 1))
    fi
  done
fi

printf 'legacy_deliverable_artifact_cleanup=ok removed=%s remaining_overlay_dirs=%s remaining_overlay_zips=%s\n' \
  "$removed" "$remaining_dirs" "$remaining_zips"
